# Generated by Django 3.2.7 on 2025-07-07 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('assunto', models.CharField(choices=[('duvidas', 'Dúvidas Gerais'), ('agendamento', 'Agendamento de Consulta'), ('suporte', 'Suporte Técnico'), ('reclamacao', 'Reclamação'), ('sugestao', 'Sugestão'), ('parceria', 'Parceria'), ('outros', 'Outros')], max_length=20, verbose_name='Assunto')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_andamento', 'Em Andamento'), ('respondido', 'Respondido'), ('resolvido', 'Resolvido')], default='novo', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resposta')),
                ('resposta', models.TextField(blank=True, verbose_name='Resposta')),
            ],
            options={
                'verbose_name': 'Mensagem de Contato',
                'verbose_name_plural': 'Mensagens de Contato',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
