"""
Django settings for saudebras project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from dotenv import load_dotenv
from pathlib import Path

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%9zlaip=y$6^+4h384l^b!!t#%w2a7n!+92wn(a5eu3$kr92!e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False  # Reativado temporariamente para debug
if not DEBUG:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_AUTOREFRESH = True
ALLOWED_HOSTS = [
    '127.0.0.1', 
    'localhost', 
    '14db-2804-1b3-6b00-a863-c1dd-ed33-5efd-eeab.ngrok-free.app', 
    'saudebras.onrender.com', 
    'saudebras.com.br',
    '955a-2804-1b3-6b00-3286-8531-64bf-c6b2-f400.ngrok-free.app', 
    '3712-2804-1b3-6b00-3286-a180-52eb-879f-bb46.ngrok-free.app', 
    'c5c4-2804-1b3-6b03-a3e5-386a-900c-bb86-8a8b.ngrok-free.app', 
    '010e-2804-1b3-6b00-1a92-6dcf-220d-cc9-f30f.ngrok-free.app',
    '*'  # Permite qualquer host (usado para desenvolvimento)
]

CSRF_TRUSTED_ORIGINS = [
    'https://c5c4-2804-1b3-6b03-a3e5-386a-900c-bb86-8a8b.ngrok-free.app', 
    'https://14db-2804-1b3-6b00-a863-c1dd-ed33-5efd-eeab.ngrok-free.app', 
    'https://3712-2804-1b3-6b00-3286-a180-52eb-879f-bb46.ngrok-free.app', 
    'https://955a-2804-1b3-6b00-3286-8531-64bf-c6b2-f400.ngrok-free.app', 
    'https://saudebras.com.br', 
    'https://010e-2804-1b3-6b00-1a92-6dcf-220d-cc9-f30f.ngrok-free.app'
]

CORS_ALLOWED_ORIGINS = ['*']

# Application definition
INSTALLED_APPS = [
    'jazzmin', 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',  # Para Supabase Storage
    'saudebras',
    'usuarios',
    'home',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # ADICIONADO AQUI
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'saudebras.middleware.ProfissionalMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'core.middleware.ErrorHandlingMiddleware' # Middleware desabilitado temporariamente
]

ROOT_URLCONF = 'saudebras.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'saudebras/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'saudebras.wsgi.application'

# Database - Supabase PostgreSQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': '5432',
        'OPTIONS': {
            'sslmode': 'require',
        },
    }
}

# Authentication
AUTHENTICATION_BACKENDS = [
    'usuarios.backends.EmailOrCpfAuthenticationBackend',
    'usuarios.backends.CaseInsensitiveModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]

AUTH_USER_MODEL = 'usuarios.CustomUser'

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True
USE_L10N = True

# ============ CONFIGURAÇÃO DE ARQUIVOS ESTÁTICOS ============

# Diretórios onde estão os arquivos estáticos
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'saudebras', 'static'),  # static do app saudebras
]

# URL para acessar arquivos estáticos
STATIC_URL = '/static/'

# Configuração mais simples para teste
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # usar pasta diferente

# ============ CONFIGURAÇÃO DE MEDIA FILES ============

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Supabase Storage Configuration
SUPABASE_URL = os.getenv('SUPABASE_URL')
SUPABASE_KEY = os.getenv('SUPABASE_KEY')
SUPABASE_BUCKET_NAME = os.getenv('SUPABASE_BUCKET_NAME', 'media')

# AWS S3 Settings for Supabase (S3 Compatible)
AWS_ACCESS_KEY_ID = os.getenv('SUPABASE_ACCESS_KEY')
AWS_SECRET_ACCESS_KEY = os.getenv('SUPABASE_SECRET_KEY')
AWS_STORAGE_BUCKET_NAME = SUPABASE_BUCKET_NAME

# Verifica se as variáveis do Supabase estão configuradas
if SUPABASE_URL and AWS_ACCESS_KEY_ID:
    AWS_S3_ENDPOINT_URL = f"{SUPABASE_URL}/storage/v1/s3"
    AWS_S3_REGION_NAME = os.getenv('SUPABASE_REGION', 'us-east-1')
    AWS_DEFAULT_ACL = 'public-read'
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_CUSTOM_DOMAIN = None
    
    # Storage backends para media files
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    MEDIA_URL = f"{SUPABASE_URL}/storage/v1/object/public/{SUPABASE_BUCKET_NAME}/"
else:
    # Fallback para armazenamento local se Supabase não estiver configurado
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
    MEDIA_URL = "/media/"

# Login/Logout
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = '/admin/login'

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'augusto.dataanalysis@gmail.com'
EMAIL_HOST_PASSWORD = 'muel jqer xnpw slqq'
DEFAULT_FROM_EMAIL = 'augusto.webdeveloping@gmail.com'
PASSWORD_RESET_EMAIL_SUBJECT = 'Redefinição de Senha do Nosso Site'
PASSWORD_RESET_TEMPLATE_NAME = 'core/mudarSenha.html'

# Stripe Configuration
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY')

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'debug.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'ERROR',
            'propagate': True,
        },
        'core.middleware': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}

# Jazzmin Configuration (Django Admin)
JAZZMIN_SETTINGS = {
    "site_title": "SAUDEBRAS",
    "site_header": "SAUDEBRAS",
    "site_brand": "SAUDEBRAS",
    "site_logo": None,
    "login_logo": None,
    "login_logo_dark": None,
    "site_logo_classes": None,
    "site_icon": True,
    "welcome_sign": "Admin SAUDEBRAS",
    "copyright": "SAUDEBRAS",
    "user_avatar": None,
    
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    
    # Configuração do menu superior com botão de logout
    "topmenu_links": [
        # Botão de logout direto (alternativa)
        {"name": "Logout", "url": "admin:logout", "icon": "fas fa-sign-out-alt"},
    ],
    
    # Links do menu do usuário (dropdown no canto superior direito)
    "usermenu_links": [
        {"name": "Perfil", "url": "admin:auth_user_change", "icon": "fas fa-user"},
        {"name": "Alterar Senha", "url": "admin:password_change", "icon": "fas fa-key"},
        {"model": "auth.user"},
        {"name": "Logout", "url": "admin:logout", "icon": "fas fa-sign-out-alt"},
    ],
    
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
    
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": False,
    "custom_js": True,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,  # Desabilitar em produção
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    "language_chooser": False,
}

# UI Tweaks - Tema Escuro Moderno
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    
    # Esquema de cores escuro - Moderno e profissional
    "brand_colour": "navbar-dark",
    "accent": "accent-light",
    "navbar": "navbar-dark navbar-gray-dark",  # Navbar escura
    "no_navbar_border": True,
    "navbar_fixed": True,
    
    # Layout escuro
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-dark",  # Sidebar completamente escura
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    
    # Tema escuro moderno
    "theme": "darkly",  # Tema escuro principal
    "dark_mode_theme": "darkly",
    
    # Botões para tema escuro
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-light",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}