# Generated by Django 4.2.5 on 2023-09-25 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='especialidades',
        ),
        migrations.DeleteModel(
            name='Especialidade',
        ),
    ]
