# Generated by Django 4.2.5 on 2023-10-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_profissional_tipo_profissional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='estado',
        ),
        migrations.AddField(
            model_name='profissional',
            name='bairro',
            field=models.ManyToManyField(blank=True, to='usuarios.bairro'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='cidade',
            field=models.ManyToManyField(blank=True, to='usuarios.cidade'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='estado',
            field=models.ManyToManyField(blank=True, to='usuarios.estado'),
        ),
    ]
