# Generated by Django 4.2.5 on 2023-10-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_profissional_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
