# Generated by Django 4.2.5 on 2023-09-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_especialidade_profissional_especialidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidade',
            name='tipo_profissional',
            field=models.CharField(blank=True, choices=[('medico', 'Médico'), ('dentista', 'Dentista')], max_length=50),
        ),
    ]
