# Generated by Django 4.2.5 on 2023-09-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_especialidade_tipo_profissional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='cpf'),
        ),
    ]
