# Generated by Django 4.2.5 on 2023-10-12 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_perguntaresposta_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos_fk', to='usuarios.clinica'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos_fk', to='usuarios.profissional'),
        ),
    ]
