# Generated by Django 4.2.5 on 2023-10-17 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_cliente_cep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='galeria/')),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos_fk', to='usuarios.clinica')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos_fk', to='usuarios.profissional')),
            ],
        ),
        migrations.AddField(
            model_name='clinica',
            name='galeria',
            field=models.ManyToManyField(blank=True, related_name='clinicas', to='usuarios.foto'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='aleria',
            field=models.ManyToManyField(blank=True, related_name='profissionais', to='usuarios.foto'),
        ),
    ]
