# Generated by Django 4.2.5 on 2023-10-19 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_foto_clinica_galeria_profissional_aleria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissional',
            old_name='aleria',
            new_name='galeria',
        ),
    ]
