# Generated by Django 4.2.5 on 2023-10-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_profissional_galeria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='galeria',
            field=models.ManyToManyField(blank=True, related_name='profissionais', to='usuarios.foto'),
        ),
    ]
