# Generated by Django 4.2.5 on 2023-10-22 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_profissional_galeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntaresposta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='usuarios.cliente'),
        ),
    ]
