# Generated by Django 4.2.5 on 2023-10-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_remove_perguntaresposta_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntaresposta',
            name='pergunta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perguntaresposta',
            name='resposta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
