# Generated by Django 4.2.5 on 2023-10-23 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_alter_perguntaresposta_pergunta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perguntaresposta',
            name='content_type',
        ),
    ]
