# Generated by Django 4.2.5 on 2023-10-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_remove_perguntaresposta_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='perguntas',
            field=models.ManyToManyField(blank=True, related_name='clinicas', to='usuarios.perguntaresposta'),
        ),
    ]
