# Generated by Django 4.2.5 on 2023-10-25 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_customuser_stripe_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('clinica', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.clinica')),
                ('profissional', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.profissional')),
            ],
        ),
    ]
