# Generated by Django 4.2.5 on 2023-10-25 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='clinica',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.clinica'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='profissional',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.profissional'),
        ),
    ]
