# Generated by Django 4.2.5 on 2023-10-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_alter_subscription_clinica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
    ]
