# Generated by Django 4.2.5 on 2023-10-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_alter_customuser_email_alter_customuser_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('foto', models.ImageField(default='/images/unknown.png', upload_to='images/')),
            ],
        ),
    ]
