# Generated by Django 4.2.5 on 2023-11-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0025_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='diploma',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
