# Generated by Django 4.2.7 on 2023-11-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0026_profissional_diploma'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='preco',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
