# Generated by Django 4.2.7 on 2024-07-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0027_profissional_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
