# Generated by Django 4.2.7 on 2024-07-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0028_cliente_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rua',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
