# Generated by Django 4.2.7 on 2024-07-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0029_cliente_rua'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ddd',
            field=models.CharField(blank=True, max_length=2, verbose_name='DDD'),
        ),
    ]
