# Generated by Django 4.2.7 on 2024-07-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0030_customuser_ddd'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
